---
title: "36-315"
author: "Group Number: 19, Names: Julien Naegeli, Alex Frazier, Johnny Wu, Maria Rodriguez: jnaegeli, afrazie1, johnnywu, mar1"
date: "Due Monday"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show

---


```{r}
library(dplyr)
library(readr)

indicators <- read_csv("Indicators.csv")

countsCountry <- indicators %>%
  group_by(CountryCode, CountryName) %>%
  summarise(NumIndicators = n_distinct(IndicatorName),
            NumYears      = n_distinct(Year),
            FirstYear     = min(Year),
            LastYear      = max(Year))

countsIndicate <- indicators %>%
  group_by(IndicatorCode, IndicatorName) %>%
  summarise(NumCountries = n_distinct(CountryName),
            NumYears     = n_distinct(Year),
            FirstYear    = min(Year),
            LastYear     = max(Year))

# Note - $ being replaced with dollar to avoid MathJax issue
#counts$IndicatorName <- gsub("\\$", "dollar", counts$IndicatorName)
#print.table(counts)
```

Graphings
```{r}

country_sub <- indicators %>% 
  group_by(CountryName, Year) %>%
  filter(CountryName == "United States" |
           CountryName == "Botswana" | 
           CountryName == "China" |
           CountryName == "Dominican Republic")


us_data <- indicators %>% 
  group_by(CountryName, Year) %>%
  filter(CountryName == "United States")


net_migration <- indicators %>% 
  group_by(CountryName, Year) %>%
  filter(IndicatorName == "Urban population")
         
#  IndicatorName == "Refugee population by country or territory of asylum" |
# IndicatorName == "Refugee population by country or territory of origin")

wrld <- filter(net_migration, CountryName == "World")

library(ggplot2)  

ggplot(wrld, aes(x = Year, y = Value)) + geom_line() + scale_x_continuous(expand = c(.001, .001))

ggplot(net_migration, aes(x = Year, y = Value, color = CountryName)) + geom_point() + 
  guides(color=FALSE)
 
```