---
title: "36-315"
author: "Group Number: 19, Names: Julien Naegeli, Alex Frazier, Johnny Wu, Maria Rodriguez: jnaegeli, afrazie1, johnnywu, mar1"
date: "Due Monday"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show

---


```{r}
library(dplyr)
library(readr)
library(ggplot)

indicators <- read_csv("Indicators.csv")

countsCountry <- indicators %>%
  group_by(CountryCode, CountryName) %>%
  summarise(NumIndicators = n_distinct(IndicatorName),
            NumYears      = n_distinct(Year),
            FirstYear     = min(Year),
            LastYear      = max(Year))

countsIndicate <- indicators %>%
  group_by(IndicatorCode, IndicatorName) %>%
  summarise(NumCountries = n_distinct(CountryName),
            NumYears     = n_distinct(Year),
            FirstYear    = min(Year),
            LastYear     = max(Year))

# Note - $ being replaced with dollar to avoid MathJax issue
#counts$IndicatorName <- gsub("\\$", "dollar", counts$IndicatorName)
#print.table(counts)
```

Graphings
```{r}
gdp_mortality_debt_allCountry <- indicators %>% 
  group_by(CountryName, Year, IndicatorName) %>%
  filter(IndicatorName == "GDP (current LCU)" |
         IndicatorName == "Mortality rate, under-5 (per 1,000)" | 
         IndicatorName == "Central government debt, total (% of GDP)" | 
         IndicatorName == "Military expenditure (% of GDP)")



south_america <- gdp_mortality_debt_allCountry %>%
  filter(CountryName == "Brazil" |
         CountryName == "Argentina" | 
         CountryName == "Paraguay" | 
         CountryName == "Uruguay" |
         CountryName == "Chile" | 
         CountryName == "Bolivia" | 
         CountryName == "Peru" | 
         CountryName == "Ecuador" | 
         CountryName == "Colombia" | 
         CountryName == "Venezuela" | 
         CountryName == "Guyana" | 
         CountryName == "Suriname" )


gdpL <- filter(south_america, IndicatorName == "GDP (current LCU)")
nationalDebt <- filter(south_america, IndicatorName == "Central government debt, total (% of GDP)")

ggplot(nationalDebt, aes(x = "Central government debt, total (% of GDP)", y = "Military expenditure")) + geom_point() + 
  labs(
    title = "Government Debt vs Military Expenditure",
    x = "Central government debt total (% of GDP)",
    y = "Military expenditure (% of GDP)"
  )

ggplot(gdpL, aes("GDP (current LCU)", "Mortality rate, under-5 (per 1,000)")) + geom_bar() + 
  labs(
    title = "GDP vs Mortality Rate",
    x = "GDP (current LCU)",
    y = "Mortality rate, under-5 (per 1,000)"
  )


```






