---
title: "36-315 Static Graphics Group Project, Spring 2017"
author: "Group Number: 19, Names: Julien Naegeli, Alex Frazier, Johnny Wu, Maria Rodriguez: jnaegeli, afrazie1, johnnywu, mar1"
date: "April 13, 2017"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show

---


```{r}
library(dplyr)
library(readr)
# install.packages("sp", dependencies = T)
# install.packages("ggmap")
library(sp)
library(ggmap)

indicators <- read_csv("../Indicators.csv")
```

```{r}
# vector of variables of interest for subsetting
variables_of_interest <- c("NY.GDP.PCAP.CN", "NY.GDP.MKTP.CN",
                           "MS.MIL.XPND.GD.ZS", "SP.DYN.AMRT.FE",
                           "SP.DYN.AMRT.MA", "SP.DYN.IMRT.IN", 
                           "SP.DYN.CDRT.IN", "SP.DYN.CBRT.IN",
                           "SP.POP.TOTL", "SE.ADT.LITR.ZS", 
                           "BX.GSR.GNFS.CD", "BM.GSR.GNFS.CD",
                           "IC.FRM.CORR.ZS", "SP.DYN.LE00.IN",
                           "SL.UEM.TOTL.ZS", "NY.GNP.ATLS.CD", 
                           "NY.GDP.MKTP.KD.ZG", "NY.GDP.MKTP.KD")

# Get unique country names for subsetting
unique_country_names <- unique(indicators$CountryName)
world_powers <- c("United States", "China", "Japan", "Germany", "France", 
                  "United Kingdom", "Russian Federation")

# The first 32 countries are regions that incorporate multiple countries
# For our purposes, we are only interested in the individual countries
actual_countries <- setdiff(unique_country_names[33:length(unique_country_names)],
                            c("Tuvalu", "Macao SAR, China", "Hong Kong SAR, China",
                              "St. Kitts and Nevis", "Antigua and Barbuda", 
                              "Trinidad and Tobago", "St. Vincent and the Grenadines", 
                              "Channel Islands"))

# Subset data based on country and variable
world_df <- subset(indicators, 
                   IndicatorCode %in% variables_of_interest &
                   CountryName %in% actual_countries)

# Recode country names to interact with world map
world_df$CountryName <- recode(world_df$CountryName, 
       "Bahamas, The" = "Bahamas", 
       "Brunei Darussalam" = "Brunei",
       "Cote d'Ivoire" = "Ivory Coast", 
       "Congo, Dem. Rep." = "Democratic Republic of the Congo",
       "Congo, Rep." = "Republic of Congo",
       "Cabo Verde" = "Cape Verde", 
       "Gambia, The" = "Gambia",
       "Micronesia, Fed. Sts." = "Micronesia",
       "Russian Federation" = "Russia",
       "Egypt, Arab Rep." = "Egypt",
       "Macedonia, FYR" = "Macedonia",
       "Syrian Arab Republic" = "Syria",
       "Faeroe Islands" = "Faroe Islands",
       "Iran, Islamic Rep." = "Iran",
       "Lao PDR" = "Laos",
       "Slovak Republic" = "Slovakia",
       "St. Martin (French part)" = "Saint Martin",
       "Sint Maarten (Dutch part)" = "Sint Maarten",
       "St. Lucia" = "Saint Lucia",
       "Venezuela, RB" = "Venezuela",
       "Korea, Dem. Rep." = "North Korea",
       "Korea, Rep." = "South Korea",
       "West Bank and Gaza" = "Palestine",
       "Yemen, Rep." = "Yemen",
       "Kyrgyz Republic" = "Kyrgyzstan")

map_df <- map_data(map = "world")

map_df$region <- recode(map_df$region, 
                       "UK" = "United Kingdom",
                       "USA" = "United States",
                       "Virgin Islands" = "Virgin Islands (U.S.)")

# unwanted <- c("Saint Barthelemy", "Anguilla", "Antarctica", "Martinique",
#   "French Southern and Antarctic Lands", "Cook Islands", "Canary Islands", 
#   "Falkland Islands", "Reunion", "Mayotte", "French Guiana", "Guadeloupe", 
#   "Heard Island", "Cocos Islands", "Christmas Island", "Chagos Archipelago",
#   "Siachen Glacier", "Montserrat", "Norfolk Island", "Niue", "Bonaire", 
#   "Sint Eustatius", "Saba", "Nauru", "Pitcairn Islands", "Madeira Islands",
#   "Azores", "Western Sahara", "South Sandwich Islands", "South Georgia", 
#   "Saint Helena", "Ascension Island", "Saint Pierre and Miquelon",
#   "Taiwan", "Wallis and Futuna", "Nevis", "Saint Kitts", "Antigua", "Barbuda", 
#   "Trinidad", "Tobago", "Grenadines", "Saint Vincent", "Jersey", "Vatican",
#   "Guernsey")
# 
# wanted_countries <- setdiff(unique(map_df$region), unwanted)
# 
# map_df <- subset(map_df, region %in% wanted_countries)

# Add new columns
world_df <- mutate(world_df,
                   is_world_power = ifelse(CountryName %in% world_powers, 
                                           "Yes", "No"))
```

```{r}
full_country_df <- merge(w_2015_df, map_df, by.x = "CountryName", by.y = "region")
library(xlsx)
write.xlsx(mydata, "c:/mydata.xlsx")
```

```{r}
#  [1] "SP.DYN.CBRT.IN"    "SP.DYN.CDRT.IN"    "SP.DYN.AMRT.FE"    "SP.DYN.AMRT.MA"   
#  [5] "SP.DYN.IMRT.IN"    "SP.POP.TOTL"       "NY.GDP.MKTP.CN"    "NY.GDP.PCAP.CN"   
#  [9] "SE.ADT.LITR.ZS"    "MS.MIL.XPND.GD.ZS" "IC.FRM.CORR.ZS"    "BX.GSR.GNFS.CD"   
# [13] "BM.GSR.GNFS.CD"   "NY.GNP.ATLS.CD", "NY.GDP.MKTP.KD.ZG"
jnaegeli_315_theme <-  theme_bw() + 
  theme(
    axis.text = element_text(size = 10, family = "Calibri", 
                                 color = "royalblue4"),
        text = element_text(size = 14, family = "Calibri",
                            face = "bold", color = "grey30"))


w_2015_df <- subset(world_df, Year == 2007 & IndicatorCode == "NY.GDP.MKTP.KD")
names(w_2015_df)[names(w_2015_df) == "CountryName"] <- "region"
full_map_df <- merge(map_df, w_2015_df, by = "region",
                     all.x = TRUE)
#full_map_df$Value[is.na(full_map_df$Value)] <- "NA"
```

```{r}
p3 <- ggplot(full_map_df[order(full_map_df$order),], aes(x = long, y = lat, group = group, fill = Value))
p3 <- p3 + geom_polygon() + labs(title = "Life Expectancy at Birth by Country")+ 
  scale_fill_gradient2(low = "yellow", high = "red", 
                                     mid = "orange", midpoint = 60, name = "Average Year")+
  jnaegeli_315_theme +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.y=element_blank(), legend.position = "bottom")
p3
```

```{r}
library("PBSmapping")
library("data.table")
full_map_df <- merge(map_df, w_2015_df, by = "region",
                     all.x = TRUE)
# xlim <- c(min(full_map_df$long), max(full_map_df$long))
# ylim <- c(max(full_map_df$lat), max(full_map_df$lat))
xlim = c(-165,-90)
ylim = c(10,60)
full_map_df <- full_map_df[order(full_map_df$order),]
setnames(full_map_df, c("region","X","Y","PID","POS","subregion", "CountryCode", "IndicatorName", "IndicatorCode", "Year", "Value", "is_world_power"))
# full_map_df <- clipPolys(full_map_df, xlim = xlim, ylim = ylim, keepExtra = T)
p3 <- ggplot(full_map_df, aes(x = X, y = Y, group = PID, fill = log(Value))) +
  geom_polygon() + coord_fixed() + coord_map(projection = "mollweide") +
  labs(title = "Log Gross Domestic Product by Country") +
  scale_fill_gradient2(low = "green", high = "green4",
                                     mid = "green2", midpoint = 25,
                       name = "Log GDP")+
  jnaegeli_315_theme +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.y=element_blank(), legend.position = "bottom")
p3
```



