---
title: "36-315"
author: "Group Number: 19, Names: Julien Naegeli, Alex Frazier, Johnny Wu, Maria Rodriguez: jnaegeli, afrazie1, johnnywu, mar1"
date: "Due Monday"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show

---

```{r}
library(dplyr)
library(readr)
library(RColorBrewer)

indicators <- read_csv("../Indicators.csv")


world_powers <- c("United States", "China", "Japan", "Germany", "France", 
                  "United Kingdom", "Russian Federation")

world_powers_world <- c("United States", "China", "Japan", "Germany", "France", 
                  "United Kingdom", "Russian Federation", "World")

indicate_M <- c("GDP (current LCU)", "GDP (constant LCU)", 
                "GDP per capita (current LCU)", "GDP per capita (constant LCU)", 
                "GDP per capita growth (annual %)")

world_power_M <- indicators %>%
  filter(CountryName %in% world_powers)

world_power_MM <- indicators %>%
  filter(CountryName %in% world_powers_world)

world_gdps <- world_power_M %>% 
  filter(IndicatorName %in% indicate_M)

world_gdps_MM <- world_power_MM %>% 
  filter(IndicatorName %in% indicate_M)

gdp_all <- world_gdps_MM %>% filter(IndicatorName == "GDP per capita growth (annual %)")

a <- world_gdps %>% filter(IndicatorName == "GDP (current LCU)")
aa <- indicators %>% filter(IndicatorName == "GDP (current LCU)")

b <- world_gdps %>% filter(IndicatorName == "GDP (constant LCU)")
c <- world_gdps %>% filter(IndicatorName == "GDP per capita (current LCU)")
d <- world_gdps %>% filter(IndicatorName == "GDP per capita (constant LCU)")
e <- world_gdps %>% filter(IndicatorName == "GDP per capita growth (annual %)")

aaa <- aa %>% mutate(other = CountryName )

```

Time Series Graph of GDP Per Capita Growth % of World Powers and World
```{r}
library(scales)
library(ggplot2)
#Time Series Graph of GDP Per Capita Growth % of World Powers and World
ggplot(gdp_all, aes(x = Year, y = Value, color = CountryName)) + geom_line(size = 1.2) + 
  theme_linedraw() + scale_color_brewer(palette = "Dark2") + 
  labs(x = "Years from 1960 to 2015", y = "GDP per capita growth (annual %)", 
       title = "Annual % of GDP per capita growth of World Powers and World", 
       color = "World Powers & World") + 
  scale_x_continuous(breaks=pretty_breaks(n=15)) + 
  scale_y_continuous(breaks=pretty_breaks(n=10)) + 
  theme(text = element_text(size = 12, family = "Palatino"), 
        legend.title = element_text(size = 10))
  
```

```{r}

world_muerte <- world_power_MM %>% 
  filter(IndicatorName == "Death rate, crude (per 1,000 people)")

countryInfo <- read_csv('countries-governmentIncluded.csv')

ggplot(countryInfo, aes(x = Deathrate, y = Birthrate, color = Continent)) + geom_point() + 
  theme_linedraw() + labs(x = "Death Rate, crude (per 1,000 people)", 
                          y = "Birthratem, crude (per 1,000 people)", 
                          title = "Death Rate vs Birth Rate By Continent")


ggplot(world_muerte, aes(x = Year, y = Value, color = CountryName)) + 
  geom_line(size = 1.2) + 
  theme_linedraw() + labs(x = "Years from 1960 to 2013", y = "Death Rate, crude (per 1,000 people)", 
                          color = "World Powers & World", 
                          title = "World Powers Death Rates Over Time") + 
  scale_color_brewer(palette = "Dark2") +
  scale_x_continuous(breaks=pretty_breaks(n=15)) + 
  scale_y_continuous(breaks=pretty_breaks(n=10)) + 
  theme(text = element_text(size = 14, family = "Palatino"), 
        legend.title = element_text(size = 10))

pairs <- c("Death rate, crude (per 1,000 people)", "GINI index (World Bank estimate)")
```
